#!/usr/bin/env bash
# =============================================================================
# Generates a development CA and the TLS certificate of the local broker.
# =============================================================================
# Usage:  ./generate-dev-certs.sh [extra-name-or-ip ...]
#
# Creates in ./certs (ignored by git):
#   ca.crt / ca.key          development CA (10 years)
#   server.crt / server.key  broker certificate, with SANs for localhost,
#                            127.0.0.1, the hostname, the LAN IPs of this machine
#                            and the arguments given
# and writes ../../esp32-pzem-monitor/dev_ca.h (ignored by git) so the firmware
# trusts this CA besides the Let's Encrypt roots.
#
# An existing CA is reused (devices already flashed keep trusting it) and only
# the server certificate is issued again, e.g. when the IP of this PC changes.
# Not used in production: there the broker uses a Let's Encrypt certificate.
set -euo pipefail

here="$(cd "$(dirname "$0")" && pwd)"
certs="$here/certs"
firmware="$here/../../esp32-pzem-monitor"
mkdir -p "$certs"
cd "$certs"

if [[ ! -f ca.key || ! -f ca.crt ]]; then
  echo "Creating the development CA..."
  openssl req -x509 -newkey rsa:2048 -nodes -sha256 -days 3650 \
    -subj "/O=EnergyMonitor Dev/CN=EnergyMonitor Dev CA" \
    -keyout ca.key -out ca.crt 2>/dev/null
fi

# LAN IPv4 addresses: `hostname -I` on Linux, ipconfig on macOS.
lan_ips() {
  if hostname -I >/dev/null 2>&1; then
    hostname -I
  else
    for iface in en0 en1; do ipconfig getifaddr "$iface" 2>/dev/null || true; done
  fi
}

san="DNS:localhost,DNS:$(hostname),IP:127.0.0.1"
for ip in $(lan_ips); do
  [[ "$ip" == *:* ]] && continue   # IPv6 skipped
  san="$san,IP:$ip"
done
for extra in "$@"; do
  if [[ "$extra" =~ ^[0-9.]+$ ]]; then san="$san,IP:$extra"; else san="$san,DNS:$extra"; fi
done

echo "Issuing the broker certificate for: $san"
openssl req -newkey rsa:2048 -nodes -sha256 \
  -subj "/O=EnergyMonitor Dev/CN=energy-monitor-mqtt" \
  -keyout server.key -out server.csr 2>/dev/null
openssl x509 -req -in server.csr -CA ca.crt -CAkey ca.key -CAcreateserial \
  -days 825 -sha256 -out server.crt \
  -extfile <(printf "subjectAltName=%s\nextendedKeyUsage=serverAuth\nbasicConstraints=CA:FALSE\n" "$san") 2>/dev/null
rm -f server.csr

# The container runs as uid 1000 (the mosquitto user of the image).
chmod 644 ca.crt server.crt
chmod 640 server.key ca.key
if [[ "$(id -u)" != "1000" ]]; then
  echo "Warning: the container reads server.key as uid 1000; fix the owner if the broker does not start:"
  echo "  sudo chown 1000 $certs/server.key"
fi

{
  echo "// Generated by docker/mosquitto/generate-dev-certs.sh. DO NOT EDIT."
  echo "// Development CA of the local broker. Not versioned (.gitignore)."
  echo "#pragma once"
  echo "static const char DEV_CA_CERT[] = R\"PEM("
  cat ca.crt
  echo ")PEM\";"
} > "$firmware/dev_ca.h"

echo "Done. Restart the broker:  docker compose up -d --force-recreate"
echo "Firmware: $firmware/dev_ca.h updated; build and flash again."
